/**
 * Exploratory playthroughs to age 40 — three divergent life paths.
 * Not a correctness gate; collects findings for analysis.
 *
 * Run: npx vitest run src/tests/playtest-lives.test.js
 */
import { afterAll, afterEach, beforeEach, describe, it, expect } from 'vitest';
import { generateDynamicEvent } from '../engine/llmService';
import { MOCK_EVENT, runPlaythrough, getActivity } from './playtest/harness.js';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, '../../.playtest-reports');
const reports = [];
let randomSpy;
let dateSpy;

function seededRandom(seed) {
  let state = seed >>> 0;
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 4294967296;
  };
}

beforeEach(() => {
  vi.mocked(generateDynamicEvent).mockResolvedValue({ ...MOCK_EVENT });
  randomSpy = vi.spyOn(Math, 'random').mockImplementation(seededRandom(0x51f17e));
  let now = 1_700_000_000_000;
  dateSpy = vi.spyOn(Date, 'now').mockImplementation(() => now++);
});

afterEach(() => {
  randomSpy.mockRestore();
  dateSpy.mockRestore();
});

function writeReport(report) {
  mkdirSync(OUT_DIR, { recursive: true });
  const path = join(OUT_DIR, `${report.pathId}.json`);
  writeFileSync(path, JSON.stringify(report, null, 2));
  return path;
}

function recordReport(report) {
  reports.push(report);
  return report;
}

afterAll(() => {
  reports.forEach(writeReport);
  const outcomeRows = reports.map((report) =>
    `| ${report.pathId} | ${report.died ? `Died ${report.finalAge}` : `Alive ${report.finalAge}`} | ${report.final.career?.id ?? 'none'} | ${report.findings.length} |`
  );
  const findings = reports.flatMap((report) => report.findings);
  const findingLines = findings.length
    ? findings.map((finding) => `- **${finding.severity.toUpperCase()}** ${finding.tag} age ${finding.age}: ${finding.title} — ${finding.detail}`)
    : ['No findings.'];
  const markdown = [
    '# Playtest findings — deterministic lives to age 40',
    '',
    'Generated by `npx vitest run src/tests/playtest-lives.test.js` from the same run as the JSON snapshots.',
    '',
    '| Path | Result | Career at end | Findings |',
    '|---|---|---|---:|',
    ...outcomeRows,
    '',
    '## Findings',
    '',
    ...findingLines,
    '',
  ].join('\n');
  writeFileSync(join(OUT_DIR, 'FINDINGS.md'), markdown);
});

describe('playtest lives to age 40', () => {
  it('Path A — Academic → corporate ladder + marriage', async () => {
    const report = await runPlaythrough({
      pathId: 'path-a-corporate',
      name: 'Alex Rivera',
      targetAge: 40,
      plan: async (ctx) => {
        // Childhood: study vibe via event choices (smarts)
        await ctx.ageTo(16, 1); // Take a risk → smarts

        // Teen job
        let r = await ctx.tryAction('teen cashier', (g) => g.chooseCareer('cashier'));
        if (r.thrown) await ctx.note('high', 'Teen career threw', String(r.thrown));
        if (!ctx.result.current.career) {
          await ctx.note('medium', 'Teen cashier did not apply', ctx.result.current.history?.at(-1)?.text);
        }

        await ctx.ageTo(18, 1);

        // College
        r = await ctx.tryAction('enroll bachelor', (g) => g.enrollInDegree('bachelor'));
        if (ctx.result.current.education?.currentDegree?.type !== 'bachelor') {
          await ctx.note('high', 'Bachelor enroll failed', JSON.stringify(ctx.result.current.education));
        }

        // Work part-time through school if broke — debug cash if needed for tuition survival
        if (ctx.result.current.bank < 5000) {
          await ctx.tryAction('seed cash for tuition', (g) => g.debugModifyBank(25000));
        }

        await ctx.ageTo(22, 0);

        // After degree hopefully — get white-collar job
        const targets = ['sw_eng', 'financial_analyst', 'nurse', 'graphic_designer', 'teacher'];
        for (const id of targets) {
          if (ctx.result.current.career?.type === 'full_time') break;
          await ctx.tryAction(`apply ${id}`, (g) => g.chooseCareer(id));
        }
        if (!ctx.result.current.career || ctx.result.current.career.type === 'part_time') {
          await ctx.note('medium', 'No full-time job after college window', ctx.result.current.career?.title ?? 'none');
        }

        // Dating + marriage attempt
        await ctx.tryAction('add partner', (g) =>
          g.addRelationship({
            id: 'play_partner_a',
            name: 'Jordan Lee',
            age: 22,
            type: 'Lover',
            relation: 85,
          })
        );
        await ctx.tryAction('propose', (g) => g.proposeMarriage('play_partner_a'));
        if (ctx.result.current.relationships?.find((x) => x.id === 'play_partner_a')?.status !== 'married') {
          // boost relation and retry
          await ctx.tryAction('gift', (g) => g.giftRelationship?.('play_partner_a'));
          await ctx.tryAction('propose2', (g) => g.proposeMarriage('play_partner_a'));
        }

        // Gym once
        const gym = getActivity('mind_body', 'Gym');
        if (gym) {
          await ctx.tryAction('gym', (g) => {
            // mimic MainGame special skill path
            if (!g.consumeYearlyActivity('mind_body', gym.text, gym.yearlyLimit)) return 'blocked';
            g.trainHiddenSkill('athleticism');
            return g.triggerActivityEvent(gym.context);
          });
          await ctx.tryAction('gym again same year', (g) => {
            const ok = g.consumeYearlyActivity('mind_body', gym.text, gym.yearlyLimit);
            return ok ? 'allowed' : 'blocked';
          });
          const second = ctx.log;
          void second;
        }

        // Networking
        for (let i = 0; i < 3; i++) {
          if (ctx.result.current.bank < 200) {
            await ctx.tryAction('cash for network', (g) => g.debugModifyBank(1000));
          }
          await ctx.tryAction(`network ${i}`, (g) => g.attendNetworkingEvent());
        }

        // Invest / assets if possible
        if (ctx.result.current.bank > 10000) {
          await ctx.tryAction('buy cheap asset', (g) => {
            const catalog = g.buyAsset;
            // buyAsset signature unknown — probe
            try {
              return catalog?.('used_sedan') ?? catalog?.({ id: 'used_sedan' });
            } catch (e) {
              return String(e);
            }
          });
        }

        await ctx.ageTo(40, 0);
      },
    });

    recordReport(report);
    expect(report.finalAge).toBe(40);
    expect(report.died).toBe(false);
    expect(report.findings.filter((finding) => finding.severity === 'critical' || finding.severity === 'high')).toEqual([]);
    console.log(`[path-a] age=${report.finalAge} died=${report.died} findings=${report.findings.length}`);
    report.findings.forEach((f) => console.log(`  [${f.severity}] @${f.age} ${f.title}: ${f.detail}`));
  }, 120_000);

  it('Path B — Military → divorce / crime / hustle', async () => {
    const report = await runPlaythrough({
      pathId: 'path-b-military',
      name: 'Blake Torres',
      targetAge: 40,
      plan: async (ctx) => {
        await ctx.ageTo(18, 1); // lower karma enough to exercise the guarded crime path

        // Boost athleticism/health for enlist if needed
        const st = ctx.result.current.stats;
        if ((st.health ?? 0) < 60 || (st.athleticism ?? 0) < 50) {
          await ctx.tryAction('boost fitness', (g) => g.debugMaxStats?.());
        }

        let r = await ctx.tryAction('enlist Army', (g) => g.enlistMilitary('Army'));
        if (ctx.result.current.career?.id !== 'soldier') {
          await ctx.note('high', 'Military enlist did not set soldier career', `returned=${r.returned} career=${ctx.result.current.career?.id}`);
        }

        await ctx.ageTo(22, 0);

        // Romance then divorce
        await ctx.tryAction('date', (g) =>
          g.addRelationship({
            id: 'play_partner_b',
            name: 'Sam Quinn',
            age: 21,
            type: 'Lover',
            relation: 90,
          })
        );
        await ctx.tryAction('marry', (g) => g.proposeMarriage('play_partner_b'));
        await ctx.ageYears(2, 0);

        // Child then divorce → custody event?
        await ctx.tryAction('have child', (g) => g.haveChild('play_partner_b'));
        r = await ctx.tryAction('divorce', (g) => g.breakUp('play_partner_b'), { resolveEvent: false });
        const ex = ctx.result.current.relationships?.find((x) => x.id === 'play_partner_b');
        if (ex && (ex.status === 'married' || ex.type === 'Spouse')) {
          await ctx.note('high', 'Divorce left spouse-like state', JSON.stringify(ex));
        }
        // Resolve custody event if present
        if (ctx.result.current.currentEvent?.isCustodyBattle) {
          await ctx.tryAction('custody choice', async (g) => {
            const c = g.currentEvent.choices[1];
            g.handleChoice(c);
          });
        }

        // Crime activities
        const crime = getActivity('crime', 'Mug Someone');
        if (crime) {
          const crimeResult = await ctx.tryAction('crime', (g) => g.performActivity(crime, 'crime'));
          if (crimeResult.returned !== 'ok') await ctx.note('medium', 'Crime path did not execute', `returned=${crimeResult.returned}`);
        } else {
          const anyCrime = (await import('../config/activities.js')).ACTIVITY_MENUS.crime?.[0];
          if (anyCrime) await ctx.tryAction('crime0', (g) => g.performActivity(anyCrime, 'crime'));
        }

        // Lottery / casino
        await ctx.tryAction('lottery', (g) => g.playLottery?.(1));
        await ctx.tryAction('gamble', (g) => g.goGamble?.(100));

        // Leave military for headhunter if possible
        if (ctx.result.current.bank < 1000) {
          await ctx.tryAction('cash HH', (g) => g.debugModifyBank(5000));
        }
        r = await ctx.tryAction('headhunter', (g) => g.hireViaHeadhunter());
        if (r.returned === 'ok' && !ctx.result.current.career) {
          await ctx.note('high', 'Headhunter ok but career null', '');
        }

        await ctx.ageTo(40, 1);
      },
    });

    recordReport(report);
    expect(report.finalAge).toBe(40);
    expect(report.died).toBe(false);
    expect(report.findings.filter((finding) => finding.severity === 'critical' || finding.severity === 'high')).toEqual([]);
    console.log(`[path-b] age=${report.finalAge} died=${report.died} findings=${report.findings.length}`);
    report.findings.forEach((f) => console.log(`  [${f.severity}] @${f.age} ${f.title}: ${f.detail}`));
  }, 120_000);

  it('Path C — Startup founder + pets + lifestyle burn', async () => {
    const report = await runPlaythrough({
      pathId: 'path-c-startup',
      name: 'Casey Nguyen',
      targetAge: 40,
      plan: async (ctx) => {
        await ctx.ageTo(18, 2); // Hustle choices

        await ctx.tryAction('seed for startup', (g) => g.debugModifyBank(2000));
        let r = await ctx.tryAction('launch startup', (g) => g.startStartup());
        if (ctx.result.current.career?.id !== 'founder') {
          await ctx.note('high', 'Startup did not set founder', `returned=${r.returned}`);
        }
        // Double-start should not double-charge silently
        const bankBefore = ctx.result.current.bank;
        const secondLaunch = await ctx.tryAction('launch again', (g) => g.startStartup());
        if (secondLaunch.returned !== 'already_founder' || ctx.result.current.bank !== bankBefore) {
          await ctx.note('medium', 'Second startStartup changed active founder state', `returned=${secondLaunch.returned}; ${bankBefore} → ${ctx.result.current.bank}`);
        }

        // Adopt pet
        await ctx.tryAction('adopt', (g) => g.adoptPet?.('dog') ?? g.adoptPet?.('cat'));
        if (!(ctx.result.current.pets?.length > 0)) {
          // probe species ids
          try {
            const { PET_CATALOG } = await import('../config/petCatalog.js');
            const id = Object.keys(PET_CATALOG ?? {})[0];
            if (id) await ctx.tryAction('adopt2', (g) => g.adoptPet(id));
          } catch {
            /* ignore */
          }
        }

        // Vacations / yearly limits
        const vac = getActivity('vacation', 'Staycation');
        if (vac) {
          await ctx.tryAction('vac1', (g) => g.performActivity(vac, 'vacation'));
          const again = await ctx.tryAction('vac2 same year', (g) => g.performActivity(vac, 'vacation'));
          if (again.returned !== 'blocked_yearly') {
            await ctx.note('medium', 'Vacation yearlyLimit not enforced', `returned=${again.returned}`);
          }
        }

        // Doctor / health
        await ctx.tryAction('doctor', (g) => g.visitDoctor?.());

        // Emigrate if possible
        await ctx.tryAction('emigrate', (g) => g.emigrate?.('la') ?? g.emigrate?.('sf'));

        // Multi-partner jealousy path
        await ctx.tryAction('lover1', (g) =>
          g.addRelationship({ id: 'l1', name: 'Pat', age: 20, type: 'Lover', relation: 60 })
        );
        await ctx.tryAction('lover2', (g) =>
          g.addRelationship({ id: 'l2', name: 'Riley', age: 21, type: 'Lover', relation: 60 })
        );

        await ctx.ageTo(28, 2);

        // If startup died, try special career money path
        if (!ctx.result.current.career) {
          await ctx.tryAction('reseed', (g) => g.debugModifyBank(10000));
          await ctx.tryAction('relaunch', (g) => g.startStartup());
        }

        // Buy investments if API exists
        if (ctx.result.current.bank < 1000) await ctx.tryAction('seed for investment', (g) => g.debugModifyBank(2000));
        const { FUND_LIST } = await import('../config/investmentMarket.js');
        const investment = await ctx.tryAction('buy index fund', (g) => g.buyInvestment(FUND_LIST[0], 1000, 'fund'));
        if (investment.returned !== 'ok') await ctx.note('medium', 'Valid investment did not execute', `returned=${investment.returned}`);

        await ctx.ageTo(40, 2);
      },
    });

    recordReport(report);
    expect(report.finalAge).toBe(40);
    expect(report.died).toBe(false);
    expect(report.findings.filter((finding) => finding.severity === 'critical' || finding.severity === 'high')).toEqual([]);
    console.log(`[path-c] age=${report.finalAge} died=${report.died} findings=${report.findings.length}`);
    report.findings.forEach((f) => console.log(`  [${f.severity}] @${f.age} ${f.title}: ${f.detail}`));
  }, 120_000);
});
