export const PET_CATALOG = {
  dog: {
    id: 'dog',
    species: 'Dog',
    icon: '🐕',
    adoptCost: 500,
    annualMaintenanceCost: 800,
    happinessBonus: 5,
    lifespanMin: 10,
    lifespanMax: 15,
    namePool: ['Buddy', 'Max', 'Bella', 'Charlie', 'Luna', 'Cooper', 'Daisy', 'Milo'],
  },
  cat: {
    id: 'cat',
    species: 'Cat',
    icon: '🐈',
    adoptCost: 200,
    annualMaintenanceCost: 500,
    happinessBonus: 3,
    lifespanMin: 12,
    lifespanMax: 18,
    namePool: ['Whiskers', 'Luna', 'Oliver', 'Bella', 'Shadow', 'Simba', 'Mittens', 'Tiger'],
  },
  rabbit: {
    id: 'rabbit',
    species: 'Rabbit',
    icon: '🐇',
    adoptCost: 100,
    annualMaintenanceCost: 300,
    happinessBonus: 2,
    lifespanMin: 6,
    lifespanMax: 10,
    namePool: ['Thumper', 'Biscuit', 'Cotton', 'Hazel', 'Pepper', 'Cinnamon'],
  },
  exotic: {
    id: 'exotic',
    species: 'Exotic Pet',
    icon: '🦜',
    adoptCost: 2000,
    annualMaintenanceCost: 1500,
    happinessBonus: 4,
    lifespanMin: 8,
    lifespanMax: 20,
    namePool: ['Rio', 'Polly', 'Kiwi', 'Mango', 'Jasper', 'Phoenix'],
  },
};
